SELECT ?AREAGEOGRAFICA ?REGIONE ?PROVINCIA
WHERE { 
	GRAPH ?G {
		?CODICESCUOLA miur:AREAGEOGRAFICA ?AREAGEOGRAFICA.
		?CODICESCUOLA miur:REGIONE ?REGIONE.
		?CODICESCUOLA miur:PROVINCIA ?PROVINCIA.
		?CODICESCUOLA miur:CODICESCUOLA "GERC004014".
	}
}
GROUP BY ?AREAGEOGRAFICA ?REGIONE ?PROVINCIA
ORDER BY ?AREAGEOGRAFICA ?REGIONE ?PROVINCIA
LIMIT 50



SELECT ?CODICEISTITUTORIFERIMENTO, ?DENOMINAZIONEISTITUTORIFERIMENTO 
WHERE { 
	GRAPH ?G {
		?CODICESCUOLA miur:CODICEISTITUTORIFERIMENTO ?CODICEISTITUTORIFERIMENTO.
		?CODICESCUOLA miur:DENOMINAZIONEISTITUTORIFERIMENTO ?DENOMINAZIONEISTITUTORIFERIMENTO.
		?CODICESCUOLA miur:CODICESCUOLA "CBSL00201A".
	}
}
GROUP BY ?CODICEISTITUTORIFERIMENTO, ?DENOMINAZIONEISTITUTORIFERIMENTO
ORDER BY ?CODICEISTITUTORIFERIMENTO, ?DENOMINAZIONEISTITUTORIFERIMENTO
LIMIT 50


SELECT (str(?ANNO) as ?ANNOSCOLASTICO) ?AREAGEOGRAFICA ?REGIONE ?PROVINCIA (?DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA AS ?GRADOISTRUZIONE) (COUNT(?CODICESCUOLA) AS ?NUMEROSCUOLE)
 WHERE { 
	GRAPH ?G {
		?CODICESCUOLA miur:ANNOSCOLASTICO ?ANNO;
		miur:AREAGEOGRAFICA ?AREAGEOGRAFICA;
		miur:REGIONE ?REGIONE;
		miur:PROVINCIA ?PROVINCIA;
		miur:DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA ?DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA.
	}
}
GROUP BY ?ANNO ?AREAGEOGRAFICA ?REGIONE ?PROVINCIA ?DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA
ORDER BY ?AREAGEOGRAFICA ?REGIONE ?PROVINCIA ?DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA
LIMIT 50














PREFIX miur: <http://www.miur.it/ns/miur#>
Select ?AnnoScolastico ?AreaGeografica ?Regione ?Provincia ?CodiceIstitutoRiferimento ?DenominazioneIstitutoRiferimento ?CodiceScuola ?DenominazioneScuola ?IndirizzoScuola ?CAPScuola ?CodiceComuneScuola ?DescrizioneComune ?DescrizioneCaratteristicaScuola ?DescrizioneTipologiaGradoIstruzioneScuola ?IndicazioneSedeDirettivo ?IndicazioneSedeOmnicomprensivo ?IndirizzoEmailScuola ?IndirizzoPecScuola ?SitoWebScuola ?SedeScolastica {
    graph ?g {
        ?S miur:ANNOSCOLASTICO ?AnnoScolastico.
        ?S miur:AREAGEOGRAFICA ?AreaGeografica.
        ?S miur:CAPSCUOLA ?CAPScuola.
        ?S miur:CODICECOMUNESCUOLA ?CodiceComuneScuola.
        ?S miur:CODICEISTITUTORIFERIMENTO ?CodiceIstitutoRiferimento.
        ?S miur:CODICESCUOLA ?CodiceScuola.
        ?S miur:DENOMINAZIONEISTITUTORIFERIMENTO ?DenominazioneIstitutoRiferimento.
        ?S miur:DENOMINAZIONESCUOLA ?DenominazioneScuola.
        ?S miur:DESCRIZIONECARATTERISTICASCUOLA ?DescrizioneCaratteristicaScuola.
        ?S miur:DESCRIZIONECOMUNE ?DescrizioneComune.
        ?S miur:DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA ?DescrizioneTipologiaGradoIstruzioneScuola.
        ?S miur:INDICAZIONESEDEDIRETTIVO ?IndicazioneSedeDirettivo.
        ?S miur:INDICAZIONESEDEOMNICOMPRENSIVO ?IndicazioneSedeOmnicomprensivo.
        ?S miur:INDIRIZZOEMAILSCUOLA ?IndirizzoEmailScuola.
        ?S miur:INDIRIZZOPECSCUOLA ?IndirizzoPecScuola.
        ?S miur:INDIRIZZOSCUOLA ?IndirizzoScuola.
        ?S miur:PROVINCIA ?Provincia.
        ?S miur:REGIONE ?Regione.
        ?S miur:SITOWEBSCUOLA ?SitoWebScuola.
        optional {
            ?S miur:SEDESCOLASTICA ?SedeScolastica
        }
    }
}
LIMIT 50




PREFIX miur: <http://www.miur.it/ns/miur#>
Select ?CodiceIstitutoRiferimento ?DenominazioneIstitutoRiferimento {
    graph ?g {
        ?S miur:CODICEISTITUTORIFERIMENTO ?CodiceIstitutoRiferimento.
        ?S miur:DENOMINAZIONEISTITUTORIFERIMENTO ?DenominazioneIstitutoRiferimento.
        ?S miur:CODICESCUOLA "CBSL00201A".
    }
}
LIMIT 50

