PREFIX miur: <http://www.miur.it/ns/miur#>
Select ?CodiceScuola ?DenominazioneScuola ?IndirizzoScuola ?DescrizioneComune
?CapScuola ?IndirizzoEmailScuola {
    graph ?g {
        ?S miur:CODICESCUOLA 'PNTL012017'.
        ?S miur:CODICESCUOLA ?CodiceScuola.
        ?S miur:DENOMINAZIONESCUOLA ?DenominazioneScuola.
        ?S miur:INDIRIZZOSCUOLA ?IndirizzoScuola.
        ?S miur:DESCRIZIONECOMUNE ?DescrizioneComune.
        ?S miur:CAPSCUOLA ?CapScuola.
        ?S miur:INDIRIZZOEMAILSCUOLA ?IndirizzoEmailScuola.
    }
}
Limit 1

